export const ProjectsData = [
  {
    title: 'Pen & Paper - VisualBasic',
    description: "Digitales Tool ersetzt Stift und Papier",
    image: './images/penandpaper.png',
    tags: ['Retro', 'VB', '2017'],
    more: '#',
    code: '#',
    id: 0,
  },
  {
    title: 'Pen & Paper - Unity',
    description: "Digitales Tool ersetzt Stift und Papier",
    image: './images/penandpaper.png',
    tags: ['Unity', 'C#', '2018'],
    more: '#',
    code: '#',
    id: 1,
  },
  {
    title: 'Altes Portfolio',
    description: "Alte Version aus 2020-2021",
    image: './images/oldportfolio.png',
    tags: ['HTML', 'CSS', 'JavaScript' , '2020', '2021'],
    more: '/Projects/Portfolio_2020-2021/index.php',
    code: '#',
    id: 2,
  },
  {
    title: 'PartyBox',
    description: "Die Spielesammlung auf deinem Handy",
    image: './images/partybox.png',
    tags: ['Unity', 'C#', '2020'],
    more: '#',
    code: '#',
    id: 3,
  },
  {
    title: 'Neues Portfolio',
    description: "Das neue Portfolio seit 2022",
    image: './images/oldportfolio.png',
    tags: ['React', 'Node.js', '2022'],
    more: 'https://www.danny-sinicco.de',
    code: 'https://github.com/Teshiification/Portfolio',
    id: 4,
  },
];
